apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  # This is where deployment know what pod(s) to manage 
  # Must match matchLabels & Service component selector label
  template:
    metadata:
      labels: 
        app: tickets
    # This is where we tell the pod how to behave
    spec:
      containers:
      - name: tickets
       image: daochat/tickets:latest
        # NOTE: create secret object first before setting it up in here
        env:
          - name: NATS_CLUSTER_ID
            value: 'ticketing'
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name # pods name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP # optional, ClusterIP will still be the default
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000
